<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerBCcAum0\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerBCcAum0/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerBCcAum0.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerBCcAum0\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerBCcAum0\App_KernelDevDebugContainer([
    'container.build_hash' => 'BCcAum0',
    'container.build_id' => 'da200181',
    'container.build_time' => 1707921008,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerBCcAum0');
