<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerR5tMAka\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerR5tMAka/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerR5tMAka.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerR5tMAka\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerR5tMAka\App_KernelDevDebugContainer([
    'container.build_hash' => 'R5tMAka',
    'container.build_id' => 'df228de0',
    'container.build_time' => 1708114191,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerR5tMAka');
