<?php

namespace ContainerBCcAum0;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getWebSocketLauncherCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\WebSocketLauncherCommand' shared autowired service.
     *
     * @return \App\Command\WebSocketLauncherCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/console/Command/Command.php';
        include_once \dirname(__DIR__, 4).'/src/Command/WebSocketLauncherCommand.php';

        $container->privates['App\\Command\\WebSocketLauncherCommand'] = $instance = new \App\Command\WebSocketLauncherCommand();

        $instance->setName('app:listener:websocket');
        $instance->setDescription('Starts the WebSocket server for the chat application.');

        return $instance;
    }
}
